name: Syncer
description: Sync file to mirror in Los Angeles

inputs:
  local:
    description: local file path
    required: true
  remote:
    description: remote file path
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        cat << 'EOF' > ~/.ssh/rw_key
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACCuFTCZ/HHjcEQG3RMMRRifRej/FLcv28RuO4ici8RlFwAAAJB1VI7NdVSO
        zQAAAAtzc2gtZWQyNTUxOQAAACCuFTCZ/HHjcEQG3RMMRRifRej/FLcv28RuO4ici8RlFw
        AAAEB2NKbIQ4oUhqiVvx/rA2F1kc0gbRdsBeUu9XpBLCoNYK4VMJn8ceNwRAbdEwxFGJ9F
        6P8Uty/bxG47iJyLxGUXAAAABmdoc3luYwECAwQFBgc=
        -----END OPENSSH PRIVATE KEY-----
        EOF
        chmod 600 ~/.ssh/rw_key
        ssh-keyscan l.867678.xyz >> ~/.ssh/known_hosts

    - name: Conexionario
      shell: bash
      run: |
        rsync -avz --delete \
            -e "ssh -i ~/.ssh/rw_key -p 22" \
            ${{ inputs.local }} \
            root@l.867678.xyz:${{ inputs.remote }}
