name: Syncer
description: Sync file to mirror in Los Angeles

inputs:
  local:
    description: local file path
    required: true
  remote:
    description: remote file path
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        curl -LO https://r2.867678.xyz/cc_la_key > ~/.ssh/rw_key
        chmod 600 ~/.ssh/rw_key
        ssh-keyscan l.867678.xyz >> ~/.ssh/known_hosts

    - name: Conexionario
      shell: bash
      run: |
        rsync -avz --delete \
            -e "ssh -i ~/.ssh/rw_key -p 22" \
            ${{ inputs.local }} \
            root@l.867678.xyz:${{ inputs.remote }}
