name: Syncer
description: Sync file to mirror

inputs:
  local:
    description: local file path
    required: true
  remote:
    description: remote file path
    required: true
  extra:
    description: extra arguments
    required: false

runs:
  using: "composite"
  steps:
    - name: Conexionario
      shell: bash
      run: |
        rsync -avzh --progress ${{ inputs.extra }} ${{ inputs.local }} l.867678.xyz::${{ inputs.remote }}
