name: 'Install Build Dependencies'
description: 'Install Build Dependencies'
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
          sudo apt update
          sudo apt install build-essential libncursesw5-dev \
          gettext xsltproc python3-pyelftools
