name: Build pnpm and nodejs project
description: Fuck the pnpm and nodejs

inputs:
  pnpm:
    description: needs pnpm
    required: false
    default: yes
  command:
    description: extra build commands
    required: false
    default: |
      pnpm install
      pnpm build
  wrangler:
    description: send compile file to cloudflare serverless
    required: false
  wrangler-apiToken:
    description: wrangler token
    required: false
  wrangler-command:
    description: wrangler command
    required: false
  release:
    description: do you want release compile files
    required: false
  release-get_version:
    description: do you want get your project version from package.json
    required: false
    default: yes
  release-tag_name:
    description: release tag name
    required: false
  release-files:
    description: release files
    required: false
  release-body:
    description: release body
    required: false
    default: |
      # 📝 Release Notes
      - Fixes and improvements
  rsync:
    description: do you want sync to mirror
    required: false
  rsync-local:
    description: rsync local path
    required: false
  rsync-remote:
    description: rsync remote path
    required: false
  rsync-key:
    description: rsync peer server key
    required: false
  rsync-server:
    description: rsync remote server
    required: false
    default: la.867678.xyz
  rsync-extra:
    description: rsync extra arguments
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: latest

    - name: Set up pnpm
      if: ${{ inputs.pnpm == 'yes' }}
      uses: pnpm/action-setup@master

    - name: Build!
      shell: bash
      run: |
        ${{ inputs.command }}

    - name: Sent to Cloudflare
      if: ${{ inputs.wrangler == 'yes' }}
      uses: cloudflare/wrangler-action@v4.1.1
      with:
        apiToken: ${{ inputs.wrangler-apiToken }}
        command: ${{ inputs.wrangler-command }}

    - name: Get version
      if: ${{ inputs.release == 'yes' && inputs.release-get_version == 'yes' }}
      id: get_version
      shell: bash
      run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: softprops/action-gh-release@master
      if: ${{ inputs.release == 'yes' }}
      with:
        tag_name: ${{ inputs.release-tag_name || format('v{0}', steps.get_version.outputs.version) }}
        files: ${{ inputs.release-files }}
        body: |
          ${{ inputs.release-body }}

    - name: Send to mirror
      uses: moaeiou/moaeiou/actions/rsync@main
      if: ${{ inputs.rsync == 'yes' }}
      with:
        local: ${{ inputs.rsync-local }}
        remote: ${{ inputs.rsync-remote }}
        key: ${{ inputs.rsync-key }}
        extra: ${{ inputs.rsync-extra }}
        server: ${{ inputs.rsync-server }}
