name: Prepare SDK
description: Unified SDK preparation for multiple architectures
inputs:
  sdk_arch:
    description: SDK arch name
    required: true
  gcc_version:
    description: Upstream GCC version
    required: true
    default: "14.4.0"
outputs:
  sdk_dir:
    description: Extracted SDK directory name for downstream use
    value: ${{ steps.sdk_dir.outputs.dir_name }}

runs:
  using: "composite"
  steps:
    - name: Get SDK Full Directory Name
      id: sdk_dir
      shell: bash
      run: |
        echo "dir_name=openwrt-sdk-${{ inputs.sdk_arch }}_gcc-${{ inputs.gcc_version }}_musl.Linux-x86_64" >> $GITHUB_OUTPUT

    - name: Download and Initialize SDK
      shell: bash
      run: |
        set -e

        ANV=$(curl -sS -I https://github.com/AnInsomniacy/aria2-next/releases/latest | grep -i '^location:' | grep -oE '[^/]+$' | tr -d '\r' | sed 's/^v//')
        wget -O aria2-next https://github.com/AnInsomniacy/aria2-next/releases/download/v$ANV/aria2-next-$ANV-linux-x86_64
        chmod +x ./aria2-next
        ./aria2-next --stream-max-connections=88 --split=88 --ca-certificate=/etc/ssl/certs/ca-certificates.crt --continue=true https://l.867678.xyz/sdk/${{ steps.sdk_dir.outputs.dir_name }}.tar.zst

        tar -xvf ${{ steps.sdk_dir.outputs.dir_name }}.tar.zst
        rm ${{ steps.sdk_dir.outputs.dir_name }}.tar.zst
        cd ${{ steps.sdk_dir.outputs.dir_name }}

        make defconfig
        ./scripts/feeds update -a
        ./scripts/feeds install -a
