name: 'Prepare SDK'
description: 'Unified SDK preparation for multiple architectures'

runs:
  using: "composite"
  steps:
    - name: Download and Initialize SDK
      shell: bash
      run: |
        set -e

        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        make defconfig
        ./scripts/feeds update -a
        ./scripts/feeds install -a
