name: Package Motrix Next

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    name: On My time
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Version checker
        id: version
        shell: bash
        run: |
          cd .github/mn/
          ./checker.sh
          source version_check_result.env
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
          if [ "$CHANGED" = "true" ]; then
            echo "new_tag=$NEW_TAG" >> "$GITHUB_OUTPUT"
          fi

      - name: Update PKGBUILD
        if: steps.version.outputs.changed == 'true'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$PKG_DIR/PKGBUILD"
          git commit -m "Bump PKGBUILD version"
          git push

  build:
    needs: bump
    runs-on: ubuntu-latest
    name: Fuck Motrix-Next!
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Prepare
        shell: bash
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel
          mv .github/mn/PKGBUILD ./PKGBUILD
          mv .github/mn/LICENSE ./LICENSE
          source PKGBUILD
          deps=("${depends[@]}" "${makedepends[@]}")
          pacman -S --needed --noconfirm "${deps[@]}"

      - name: Create build user
        shell: bash
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build!
        shell: bash
        run: |
          su builder -c "cd '$GITHUB_WORKSPACE' && makepkg -s --noconfirm --needed"

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: motrix-next
          files: ./*.pkg.tar.zst
          body: |
            # 📝 Release Notes
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
